// app/components/data.js

const artworks = [
    { image: "01.jpg", title: "The Incredulity of Saint Thomas", artist: "Caravaggio", liked: true },
    { image: "02.jpg", title: "Bacchus", artist: "Caravaggio", liked: false },
    { image: "03.jpg", title: "Judith Beheading Holofernes", artist: "Caravaggio", liked: true },
    { image: "04.jpg", title: "David with the Head of Goliath", artist: "Caravaggio", liked: false },
    { image: "05.jpg", title: "Judith Beheading Holofernes", artist: "Caravaggio", liked: true },
    { image: "06.jpg", title: "Café Terrace at Night", artist: "Vincent van Gogh", liked: false },
    { image: "07.jpg", title: "Wheatfield with Crows", artist: "Vincent van Gogh", liked: true },
    { image: "08.jpg", title: "The Starry Night", artist: "Vincent van Gogh", liked: false },
    { image: "09.jpg", title: "The birth of Venus", artist: "Sandro Botticelli", liked: true },
    { image: "10.jpg", title: "Orange and Yellow, 1956", artist: "Mark Rothko", liked: false },
    { image: "10-1.jpg", title: "Red on Maroon, 1959", artist: "Mark Rothko", liked: false },
    { image: "10-2.jpg", title: "Untitled (Black on Grey), 1970", artist: "Mark Rothko", liked: false },
    { image: "10-3.jpg", title: "No. 61 (Rust and Blue), 1953", artist: "Mark Rothko", liked: false },
    { image: "11.jpg", title: "Les Demoiselles d’Avignon", artist: "Pablo Picasso", liked: true },
    { image: "12.jpg", title: "Impression, Sunrise", artist: "Claude Monet", liked: false },
    { image: "13.jpg", title: "Nymphéas", artist: "Claude Monet", liked: true },
    { image: "14.jpg", title: "Olympia", artist: "Édouard Manet", liked: false },
    { image: "15.jpg", title: "Tahitian Women on the Beach", artist: "Paul Gauguin", liked: true },
    { image: "16.jpg", title: "The Basket of Apples", artist: "Paul Cézanne", liked: false },
    { image: "17.jpg", title: "The Baptism of Christ", artist: "Leonardo da Vinci", liked: true },
    { image: "18.jpg", title: "Saint John the Baptist", artist: "Leonardo da Vinci", liked: false },
    { image: "19.jpg", title: "The Last Supper", artist: "Leonardo da Vinci", liked: true },
    { image: "20.jpg", title: "Mona Lisa", artist: "Leonardo da Vinci", liked: false },
    { image: "21.jpg", title: "The School of Athens", artist: "Raphael", liked: true },
    { image: "22.jpg", title: "Transfiguration", artist: "Raphael", liked: false },
    { image: "23.jpg", title: "The Wedding at Cana", artist: "Paolo Veronese", liked: true },
    { image: "24.jpg", title: "Last Supper", artist: "Tintoretto", liked: false },
    { image: "25.jpg", title: "Girl with a Pearl Earring", artist: "Johannes Vermeer", liked: true },
    { image: "26.jpg", title: "The Milkmaid", artist: "Johannes Vermeer", liked: false },
    { image: "27.jpg", title: "Self-portrait", artist: "Rembrandt", liked: true },
    { image: "28.jpg", title: "The Night Watch", artist: "Rembrandt", liked: false },
    { image: "29.jpg", title: "Portrait of Wally", artist: "Egon Schiele", liked: true },
    { image: "30.jpg", title: "Self-Portrait with Chinese Lantern Plant", artist: "Egon Schiele", liked: false },
  ];

  export default artworks;